export const welcomeLinks = [
  { name: 'About', link: '/about' },
  { name: 'Help Center', link: '/help-center' },
  { name: 'Terms of Service', link: '/terms-of-service' },
  { name: 'Privacy Policy', link: '/privacy-policy' },
  { name: 'Cookie Policy', link: '/cookie-policy' },
  { name: 'Ads info', link: '/ads-info' },
  { name: 'Blog', link: '/blog' },
  { name: 'Status', link: '/status' },
  { name: 'Careers', link: '/careers' },
  { name: 'Brand Resources', link: '/brand-resources' },
  { name: 'Advertising', link: '/advertising' },
  { name: 'Marketing', link: '/marketing' },
  { name: 'Twitter for Business', link: '/twitter-for-business' },
  { name: 'Developers', link: '/developers' },
  { name: 'Directory', link: '/directory' },
  { name: 'Settings', link: '/settings' },
  { name: '© 2021 Twitter, Inc.', link: '/' },
] as const;
